#!/bin/sh

set -eu

current_os=$(uname)
current_version=$(uname -r)

required_os="NetBSD"
required_version="10.0"

if [ "$current_os" != "$required_os" ]; then
    echo "$(tput setaf 1)Wrong OS: Expected $required_os, but found $current_os"
    exit 1
fi

if [ "$current_version" != "$required_version" ]; then
    echo "$(tput setaf 1)Wrong version: Expected $required_version, but found $current_version"
    exit 1
fi

mkdir -p ~/.config/awesome/
cp /usr/pkg/share/awesome/rc.lua  ~/.config/awesome/

echo 'exec awesome' > ~/.xinitrc

echo "NetBSD Rocks!"
